### ISSUE TITLE
Terminal Emulator automatically exits after running

### ISSUE THREAD

**Issue by Mrp1r4t3** [Yisus7u7/termux-desktop-xfce#66]
![Screenshot_20211216_135522](https://user-images.githubusercontent.com/57308381/146317496-61a1f1ff-5f89-4ccf-9b51-ad35b95e8e0d.jpg)

Everytime i run terminal emulator it stays blackscreen then exit i dont know why i tried to edit the terminal emulatior launcher and change the default xfce-terminal in command ito bash,sh,etc but still it wasnt fixed.. i also tried to reinstall the desktop but still not working.

**Comment by Yisus7u7** [comment]
https://github.com/termux/x11-packages/issues/537

The error is due to the libvte packets being broken.

**Comment by Yisus7u7** [comment]
Fixed

**Comment by Mrp1r4t3** [comment]
How can i get the older version of libvte 0.62??

**Comment by Mrp1r4t3** [comment]
> How can i get the older version of libvte 0.62??



> Fixed

Uhhh how can i get the old version of libvte cuz the new version still not working
